# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label1.setFont(font)
        self.Label1.setObjectName("Label1")
        self.verticalLayout_5.addWidget(self.Label1, 0, QtCore.Qt.AlignTop)
        self.networks_list = QtWidgets.QListWidget(self.centralwidget)
        self.networks_list.setObjectName("networks_list")
        self.verticalLayout_5.addWidget(self.networks_list, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inodes_label = QtWidgets.QLabel(self.centralwidget)
        self.inodes_label.setObjectName("inodes_label")
        self.horizontalLayout_3.addWidget(self.inodes_label)
        self.inodes = QtWidgets.QLabel(self.centralwidget)
        self.inodes.setText("")
        self.inodes.setObjectName("inodes")
        self.horizontalLayout_3.addWidget(self.inodes, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hlayers_label = QtWidgets.QLabel(self.centralwidget)
        self.hlayers_label.setObjectName("hlayers_label")
        self.horizontalLayout_4.addWidget(self.hlayers_label)
        self.hlayers = QtWidgets.QLabel(self.centralwidget)
        self.hlayers.setText("")
        self.hlayers.setObjectName("hlayers")
        self.horizontalLayout_4.addWidget(self.hlayers, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.hnodes_label = QtWidgets.QLabel(self.centralwidget)
        self.hnodes_label.setObjectName("hnodes_label")
        self.horizontalLayout_5.addWidget(self.hnodes_label)
        self.hnodes = QtWidgets.QLabel(self.centralwidget)
        self.hnodes.setText("")
        self.hnodes.setObjectName("hnodes")
        self.horizontalLayout_5.addWidget(self.hnodes, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.onodes_label = QtWidgets.QLabel(self.centralwidget)
        self.onodes_label.setObjectName("onodes_label")
        self.horizontalLayout_6.addWidget(self.onodes_label)
        self.onodes = QtWidgets.QLabel(self.centralwidget)
        self.onodes.setText("")
        self.onodes.setObjectName("onodes")
        self.horizontalLayout_6.addWidget(self.onodes, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.delete_network = QtWidgets.QPushButton(self.centralwidget)
        self.delete_network.setEnabled(False)
        self.delete_network.setObjectName("delete_network")
        self.verticalLayout_5.addWidget(self.delete_network)
        self.create = QtWidgets.QPushButton(self.centralwidget)
        self.create.setObjectName("create")
        self.verticalLayout_5.addWidget(self.create)
        self.open_network = QtWidgets.QPushButton(self.centralwidget)
        self.open_network.setObjectName("open_network")
        self.verticalLayout_5.addWidget(self.open_network)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(True)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_11.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label2.setFont(font)
        self.Label2.setObjectName("Label2")
        self.verticalLayout_3.addWidget(self.Label2, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.datatype_label = QtWidgets.QLabel(self.centralwidget)
        self.datatype_label.setEnabled(False)
        self.datatype_label.setObjectName("datatype_label")
        self.horizontalLayout_8.addWidget(self.datatype_label)
        self.datatype_box = QtWidgets.QComboBox(self.centralwidget)
        self.datatype_box.setEnabled(False)
        self.datatype_box.setObjectName("datatype_box")
        self.datatype_box.addItem("")
        self.horizontalLayout_8.addWidget(self.datatype_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.training_data_label = QtWidgets.QLabel(self.centralwidget)
        self.training_data_label.setObjectName("training_data_label")
        self.verticalLayout_3.addWidget(self.training_data_label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.training_file = QtWidgets.QLabel(self.centralwidget)
        self.training_file.setText("")
        self.training_file.setObjectName("training_file")
        self.horizontalLayout_7.addWidget(self.training_file)
        self.open_training_data = QtWidgets.QPushButton(self.centralwidget)
        self.open_training_data.setObjectName("open_training_data")
        self.horizontalLayout_7.addWidget(self.open_training_data)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.testing_data_label = QtWidgets.QLabel(self.centralwidget)
        self.testing_data_label.setObjectName("testing_data_label")
        self.verticalLayout_3.addWidget(self.testing_data_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.testing_file = QtWidgets.QLabel(self.centralwidget)
        self.testing_file.setText("")
        self.testing_file.setObjectName("testing_file")
        self.horizontalLayout_9.addWidget(self.testing_file)
        self.open_testing_data = QtWidgets.QPushButton(self.centralwidget)
        self.open_testing_data.setObjectName("open_testing_data")
        self.horizontalLayout_9.addWidget(self.open_testing_data)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.lr_label = QtWidgets.QLabel(self.centralwidget)
        self.lr_label.setObjectName("lr_label")
        self.verticalLayout_3.addWidget(self.lr_label)
        self.lr_value = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lr_value.setFont(font)
        self.lr_value.setSmallDecimalPoint(False)
        self.lr_value.setDigitCount(6)
        self.lr_value.setProperty("value", 0.08)
        self.lr_value.setObjectName("lr_value")
        self.verticalLayout_3.addWidget(self.lr_value)
        self.learning_rate = QtWidgets.QSlider(self.centralwidget)
        self.learning_rate.setMinimum(1)
        self.learning_rate.setMaximum(100000)
        self.learning_rate.setProperty("value", 80000)
        self.learning_rate.setSliderPosition(80000)
        self.learning_rate.setOrientation(QtCore.Qt.Horizontal)
        self.learning_rate.setObjectName("learning_rate")
        self.verticalLayout_3.addWidget(self.learning_rate)
        self.different_lr_check = QtWidgets.QCheckBox(self.centralwidget)
        self.different_lr_check.setObjectName("different_lr_check")
        self.verticalLayout_3.addWidget(self.different_lr_check)
        self.max_lr_label = QtWidgets.QLabel(self.centralwidget)
        self.max_lr_label.setEnabled(False)
        self.max_lr_label.setObjectName("max_lr_label")
        self.verticalLayout_3.addWidget(self.max_lr_label)
        self.min_lr = QtWidgets.QSlider(self.centralwidget)
        self.min_lr.setEnabled(False)
        self.min_lr.setMinimum(1)
        self.min_lr.setMaximum(100000)
        self.min_lr.setOrientation(QtCore.Qt.Horizontal)
        self.min_lr.setObjectName("min_lr")
        self.verticalLayout_3.addWidget(self.min_lr)
        self.min_lr_label = QtWidgets.QLabel(self.centralwidget)
        self.min_lr_label.setEnabled(False)
        self.min_lr_label.setObjectName("min_lr_label")
        self.verticalLayout_3.addWidget(self.min_lr_label)
        self.max_lr = QtWidgets.QSlider(self.centralwidget)
        self.max_lr.setEnabled(False)
        self.max_lr.setMinimum(1)
        self.max_lr.setMaximum(100000)
        self.max_lr.setOrientation(QtCore.Qt.Horizontal)
        self.max_lr.setObjectName("max_lr")
        self.verticalLayout_3.addWidget(self.max_lr)
        self.epoch_size_label = QtWidgets.QLabel(self.centralwidget)
        self.epoch_size_label.setObjectName("epoch_size_label")
        self.verticalLayout_3.addWidget(self.epoch_size_label)
        self.epoch_size = QtWidgets.QLineEdit(self.centralwidget)
        self.epoch_size.setObjectName("epoch_size")
        self.verticalLayout_3.addWidget(self.epoch_size)
        self.number_of_epochs_label = QtWidgets.QLabel(self.centralwidget)
        self.number_of_epochs_label.setObjectName("number_of_epochs_label")
        self.verticalLayout_3.addWidget(self.number_of_epochs_label)
        self.epochs = QtWidgets.QLineEdit(self.centralwidget)
        self.epochs.setObjectName("epochs")
        self.verticalLayout_3.addWidget(self.epochs)
        self.training_backquery = QtWidgets.QCheckBox(self.centralwidget)
        self.training_backquery.setEnabled(False)
        self.training_backquery.setObjectName("training_backquery")
        self.verticalLayout_3.addWidget(self.training_backquery)
        self.backquery_period_label = QtWidgets.QLabel(self.centralwidget)
        self.backquery_period_label.setEnabled(False)
        self.backquery_period_label.setObjectName("backquery_period_label")
        self.verticalLayout_3.addWidget(self.backquery_period_label)
        self.backquery = QtWidgets.QLineEdit(self.centralwidget)
        self.backquery.setEnabled(False)
        self.backquery.setObjectName("backquery")
        self.verticalLayout_3.addWidget(self.backquery)
        self.testing_samples_label = QtWidgets.QLabel(self.centralwidget)
        self.testing_samples_label.setEnabled(True)
        self.testing_samples_label.setObjectName("testing_samples_label")
        self.verticalLayout_3.addWidget(self.testing_samples_label)
        self.samples = QtWidgets.QLineEdit(self.centralwidget)
        self.samples.setObjectName("samples")
        self.verticalLayout_3.addWidget(self.samples)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.backpropagation_label = QtWidgets.QLabel(self.centralwidget)
        self.backpropagation_label.setEnabled(False)
        self.backpropagation_label.setObjectName("backpropagation_label")
        self.horizontalLayout_10.addWidget(self.backpropagation_label)
        self.backpropagation_type = QtWidgets.QComboBox(self.centralwidget)
        self.backpropagation_type.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.backpropagation_type.setFont(font)
        self.backpropagation_type.setObjectName("backpropagation_type")
        self.backpropagation_type.addItem("")
        self.horizontalLayout_10.addWidget(self.backpropagation_type)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_11.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Label3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label3.setFont(font)
        self.Label3.setObjectName("Label3")
        self.verticalLayout_2.addWidget(self.Label3)
        self.start_training = QtWidgets.QPushButton(self.centralwidget)
        self.start_training.setEnabled(False)
        self.start_training.setObjectName("start_training")
        self.verticalLayout_2.addWidget(self.start_training)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_2.addWidget(self.stopButton)
        self.epoch_progress_label = QtWidgets.QLabel(self.centralwidget)
        self.epoch_progress_label.setObjectName("epoch_progress_label")
        self.verticalLayout_2.addWidget(self.epoch_progress_label)
        self.epoch_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.epoch_progress.setProperty("value", 0)
        self.epoch_progress.setObjectName("epoch_progress")
        self.verticalLayout_2.addWidget(self.epoch_progress)
        self.training_progress_label = QtWidgets.QLabel(self.centralwidget)
        self.training_progress_label.setObjectName("training_progress_label")
        self.verticalLayout_2.addWidget(self.training_progress_label)
        self.training_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.training_progress.setProperty("value", 0)
        self.training_progress.setObjectName("training_progress")
        self.verticalLayout_2.addWidget(self.training_progress)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.average_epoch_time_label = QtWidgets.QLabel(self.centralwidget)
        self.average_epoch_time_label.setObjectName("average_epoch_time_label")
        self.horizontalLayout_14.addWidget(self.average_epoch_time_label)
        self.average_epoch_time = QtWidgets.QLabel(self.centralwidget)
        self.average_epoch_time.setText("")
        self.average_epoch_time.setObjectName("average_epoch_time")
        self.horizontalLayout_14.addWidget(self.average_epoch_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.total_time_label = QtWidgets.QLabel(self.centralwidget)
        self.total_time_label.setObjectName("total_time_label")
        self.horizontalLayout_15.addWidget(self.total_time_label)
        self.total_time = QtWidgets.QLabel(self.centralwidget)
        self.total_time.setText("")
        self.total_time.setObjectName("total_time")
        self.horizontalLayout_15.addWidget(self.total_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        spacerItem1 = QtWidgets.QSpacerItem(240, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.epoch_label = QtWidgets.QLabel(self.centralwidget)
        self.epoch_label.setObjectName("epoch_label")
        self.horizontalLayout.addWidget(self.epoch_label)
        self.epoch = QtWidgets.QLabel(self.centralwidget)
        self.epoch.setText("")
        self.epoch.setObjectName("epoch")
        self.horizontalLayout.addWidget(self.epoch)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setObjectName("result_label")
        self.horizontalLayout_2.addWidget(self.result_label)
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setText("")
        self.result.setObjectName("result")
        self.horizontalLayout_2.addWidget(self.result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(240, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.best_epoch_label = QtWidgets.QLabel(self.centralwidget)
        self.best_epoch_label.setObjectName("best_epoch_label")
        self.horizontalLayout_13.addWidget(self.best_epoch_label)
        self.best_epoch = QtWidgets.QLabel(self.centralwidget)
        self.best_epoch.setText("")
        self.best_epoch.setObjectName("best_epoch")
        self.horizontalLayout_13.addWidget(self.best_epoch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.best_result_label = QtWidgets.QLabel(self.centralwidget)
        self.best_result_label.setEnabled(True)
        self.best_result_label.setObjectName("best_result_label")
        self.horizontalLayout_18.addWidget(self.best_result_label)
        self.best_result = QtWidgets.QLabel(self.centralwidget)
        self.best_result.setText("")
        self.best_result.setObjectName("best_result")
        self.horizontalLayout_18.addWidget(self.best_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        spacerItem3 = QtWidgets.QSpacerItem(240, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.save_best_network = QtWidgets.QPushButton(self.centralwidget)
        self.save_best_network.setEnabled(False)
        self.save_best_network.setObjectName("save_best_network")
        self.verticalLayout_2.addWidget(self.save_best_network)
        self.save_final_network = QtWidgets.QPushButton(self.centralwidget)
        self.save_final_network.setEnabled(False)
        self.save_final_network.setObjectName("save_final_network")
        self.verticalLayout_2.addWidget(self.save_final_network)
        self.show_stats = QtWidgets.QPushButton(self.centralwidget)
        self.show_stats.setEnabled(False)
        self.show_stats.setObjectName("show_stats")
        self.verticalLayout_2.addWidget(self.show_stats)
        self.querying_data_label = QtWidgets.QLabel(self.centralwidget)
        self.querying_data_label.setEnabled(False)
        self.querying_data_label.setObjectName("querying_data_label")
        self.verticalLayout_2.addWidget(self.querying_data_label)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.querying_number_label = QtWidgets.QLabel(self.centralwidget)
        self.querying_number_label.setEnabled(False)
        self.querying_number_label.setObjectName("querying_number_label")
        self.horizontalLayout_20.addWidget(self.querying_number_label)
        self.querying_number = QtWidgets.QLabel(self.centralwidget)
        self.querying_number.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.querying_number.setFont(font)
        self.querying_number.setText("")
        self.querying_number.setObjectName("querying_number")
        self.horizontalLayout_20.addWidget(self.querying_number)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.draw_a_number = QtWidgets.QPushButton(self.centralwidget)
        self.draw_a_number.setEnabled(False)
        self.draw_a_number.setObjectName("draw_a_number")
        self.verticalLayout_8.addWidget(self.draw_a_number)
        self.open_query_file = QtWidgets.QPushButton(self.centralwidget)
        self.open_query_file.setEnabled(False)
        self.open_query_file.setObjectName("open_query_file")
        self.verticalLayout_8.addWidget(self.open_query_file)
        self.horizontalLayout_20.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label1.setText(_translate("MainWindow", "Network Editor"))
        self.inodes_label.setText(_translate("MainWindow", "Number of input neurons:"))
        self.hlayers_label.setText(_translate("MainWindow", "Number of hidden layers:"))
        self.hnodes_label.setText(_translate("MainWindow", "Number of neurons in each hidden layer:"))
        self.onodes_label.setText(_translate("MainWindow", "Number of output neurons:"))
        self.delete_network.setText(_translate("MainWindow", "Delete"))
        self.create.setText(_translate("MainWindow", "Create new"))
        self.open_network.setText(_translate("MainWindow", "Open existing"))
        self.Label2.setText(_translate("MainWindow", "Training and testing settings"))
        self.datatype_label.setText(_translate("MainWindow", "Data type:"))
        self.datatype_box.setItemText(0, _translate("MainWindow", "Number"))
        self.label.setText(_translate("MainWindow", "Data load time can be up to a few minutes"))
        self.training_data_label.setText(_translate("MainWindow", "Training data:"))
        self.open_training_data.setText(_translate("MainWindow", "Open training data"))
        self.testing_data_label.setText(_translate("MainWindow", "Testing data:"))
        self.open_testing_data.setText(_translate("MainWindow", "Open testing data"))
        self.lr_label.setText(_translate("MainWindow", "Learning rate:"))
        self.different_lr_check.setText(_translate("MainWindow", "Different learning rate for each layer"))
        self.max_lr_label.setText(_translate("MainWindow", "Minimum rate:"))
        self.min_lr_label.setText(_translate("MainWindow", "Maximum rate:"))
        self.epoch_size_label.setText(_translate("MainWindow", "Epoch size:"))
        self.epoch_size.setText(_translate("MainWindow", "5000"))
        self.number_of_epochs_label.setText(_translate("MainWindow", "Number of epochs:"))
        self.epochs.setText(_translate("MainWindow", "5"))
        self.training_backquery.setText(_translate("MainWindow", "Backquery during training"))
        self.backquery_period_label.setText(_translate("MainWindow", "Backquery period [epochs]:"))
        self.testing_samples_label.setText(_translate("MainWindow", "Testing samples:"))
        self.samples.setText(_translate("MainWindow", "2000"))
        self.backpropagation_label.setText(_translate("MainWindow", "Backpropagation:"))
        self.backpropagation_type.setItemText(0, _translate("MainWindow", "Simplified - Transposed"))
        self.Label3.setText(_translate("MainWindow", "Training and querying"))
        self.start_training.setText(_translate("MainWindow", "Start training"))
        self.stopButton.setText(_translate("MainWindow", "Stop training"))
        self.epoch_progress_label.setText(_translate("MainWindow", "Epoch progress:"))
        self.training_progress_label.setText(_translate("MainWindow", "Training progress:"))
        self.average_epoch_time_label.setText(_translate("MainWindow", "Average epoch time:"))
        self.total_time_label.setText(_translate("MainWindow", "Total training time:"))
        self.epoch_label.setText(_translate("MainWindow", "Epoch:"))
        self.result_label.setText(_translate("MainWindow", "Result:"))
        self.best_epoch_label.setText(_translate("MainWindow", "Best epoch:"))
        self.best_result_label.setText(_translate("MainWindow", "Best result:"))
        self.save_best_network.setText(_translate("MainWindow", "Save network (best result)"))
        self.save_final_network.setText(_translate("MainWindow", "Save network (final result)"))
        self.show_stats.setText(_translate("MainWindow", "Show statistics"))
        self.querying_data_label.setText(_translate("MainWindow", "Querying data: "))
        self.querying_number_label.setText(_translate("MainWindow", "Your number is:"))
        self.draw_a_number.setText(_translate("MainWindow", "Draw a number"))
        self.open_query_file.setText(_translate("MainWindow", "Open query file"))
